### ISSUE TITLE
problems running biojs-pcviz

### ISSUE THREAD

**Issue by andrew-san** [PathwayCommons/biojs-pcviz#4]
Hello,

I am trying to use this great tool, biojs-pcviz.  I can't get it to run locally, but it is also not working on your website (http://biojs.io/d/biojs-pcviz) either, so I suspect it may be an error with the code itself.  It was also updated only yesterday, perhaps a bug was introduced.

Thanks,
Andrew

**Comment by armish** [comment]
Hi Andrew,

Thank you for reporting this to us. Our server has recently under gone some security-related changes and we had to move our embedded-widget server to another place (hence the latest change). In the process we have re-structured the way you initiate your component slightly and completely forgot to update the docs and examples to use this new approach. 

I just did this and pushed out a new release with tag `v0.3.0`. The demo page on the BioJS page should be back up and you should be able to follow the documentation to start your own instance. Please let me know if you have any issues doing so and I will be happy to help.

Thanks again and sorry about this inconvenience.
-- Arman
